min_version = "2025.1.0"

[tools]
git-cliff = "2"
python = "3.13"
ruby = "3.4"
uv = "0.10"

[env]
_.python.venv = { path = ".venv", create = true, uv_create_args = ["--seed"] }

[tasks]
pub = "uv build --clear && uv publish"

[tasks.test]
description = "Run e2e sanity tests"
run = "uv run --group test pytest tests/e2e_sanity.py --log-cli-level=INFO"
